FROM scratch

LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.description="Run command on file change"

WORKDIR /

COPY LICENSE README.md /
COPY baamhackl /

ENTRYPOINT ["/baamhackl"]

# vim: set ft=dockerfile :
