---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

# vim: set sw=2 sts=2 et :
