# Configuration for GoReleaser
# https://goreleaser.com/
#
# Local test: contrib/build-all
#

project_name: baamhackl

builds:
  - main: .
    binary: baamhackl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - -trimpath

nfpms:
  - description: Execute command when files are moved to a directory
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    dependencies:
      - watchman
    contents:
      - src: ./README.md
        dst: /usr/share/doc/baamhackl/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/baamhackl/LICENSE

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

dockers:
  - ids:
      - baamhackl
    use: buildx
    dockerfile: contrib/Dockerfile.goreleaser
    extra_files:
      - LICENSE
      - README.md
    image_templates:
      - ghcr.io/hansmi/baamhackl:{{.Tag}}
      - ghcr.io/hansmi/baamhackl:v{{.Major}}
      - ghcr.io/hansmi/baamhackl:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}

release:
  draft: true
  prerelease: auto

snapshot:
  name_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
