name: Release

on:
  workflow_dispatch:
  pull_request:
  push:

permissions: {}

jobs:
  release:
    uses: hansmi/ghactions-goreleaser-workflow/.github/workflows/release.yaml@stable
    permissions:
      contents: write
      packages: write

# vim: set sw=2 sts=2 et :
