name: Release

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Required by GoReleaser
          fetch-depth: 0

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1

      - name: Set variables
        id: vars
        env:
          EVENT_NAME: ${{ github.event_name }}
          REF: ${{ github.ref }}
        run: |
          docker_login=
          goreleaser_command=build
          goreleaser_args=( --single-target --snapshot )

          case "${EVENT_NAME:?}" in
            push | workflow_dispatch)
              if [[ "$REF" = refs/heads/main ]]; then
                goreleaser_command=release
                goreleaser_args=( --skip-publish )
              elif [[ "$REF" = refs/tags/v[0-9]*.* ]]; then
                docker_login=true
                goreleaser_command=release
                goreleaser_args=()
              fi
              ;;
          esac

          echo "docker_login=${docker_login}" >> $GITHUB_OUTPUT
          echo "goreleaser_command=${goreleaser_command}" >> $GITHUB_OUTPUT
          echo "goreleaser_args=${goreleaser_args[*]}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: steps.vars.outputs.docker_login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: ${{ steps.vars.outputs.goreleaser_command }} --rm-dist ${{ steps.vars.outputs.goreleaser_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: baamhackl-${{ hashFiles('dist/**') }}
          path: dist/**
          if-no-files-found: error

# vim: set sw=2 sts=2 et : -->
